urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('new', views.CustomerCreateView.as_view(), name='new'),  
  path('<int:pk>/', views.OrderDetailView.as_view(), name='order'),
  path('customer/<int:pk>', views.CustomerUpdateView.as_view(), name='customer-update'),
  path('<order_id>/item/new', views.OrderItemCreateView.as_view(), name='orderitem-create'),
  path('item/<int:pk>', views.OrderItemUpdateView.as_view(), name='orderitem-update'),
  path('item/<int:pk>/delete', views.OrderItemDeleteView.as_view(), name='orderitem-delete'),
  path('<order_id>/note/new', views.NoteCreateView.as_view(), name='note-create'),
  path('note/<int:pk>', views.NoteUpdateView.as_view(), name='note-update'),
  path('note/<int:pk>/delete', views.NoteDeleteView.as_view(), name='note-delete'),
  path('suppliers', views.SuppliersView.as_view(), name='suppliers'),
  path('supplier/new', views.SupplierCreateView.as_view(), name='supplier-new'),
  path('supplier/<int:pk>', views.SupplierUpdateView.as_view(), name='supplier-update'),
  path('supplier/<int:pk>/delete', views.SupplierDeleteView.as_view(), name='supplier-delete'),
  path('brands', views.BrandsView.as_view(), name='brands'),
  path('brand/new', views.BrandCreateView.as_view(), name='brand-new'),
  path('brand/<int:pk>', views.BrandUpdateView.as_view(), name='brand-update'),
  path('purchases', views.PurchasesView.as_view(), name='purchases'),
]

models.py
from django.db import models
from django.db.models.signals import post_save, post_delete

class Customer(models.Model):
  name = models.CharField(max_length=50)
  email = models.CharField(max_length=50)
  phone = models.CharField(max_length=15)
  city = models.CharField(max_length=50)
  address = models.CharField(max_length=100)
  postcode = models.CharField(max_length=8)

  def __str__(self):
    return self.name


class Webshop(models.Model):
  name = models.CharField(max_length=30)
  uri = models.CharField(max_length=40)

  def __str__(self):
    return self.name


class Order(models.Model):
  customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
  webshop = models.ForeignKey(Webshop, on_delete=models.PROTECT, verbose_name='Webshop')
  original = models.CharField(max_length=15, blank=True)

  def total(self):
    items = OrderItem.objects.filter(order=self.id)
    sum = 0
    for item in items:
      sum += item.price * item.quantity
    return sum

  def get_suppliers(self):
    items = OrderItem.objects.filter(order=self.id)
    partners = []

    for item in items:
      if item.brand.supplier.name not in partners:
        partners.append(item.brand.supplier.name)
    return partners

  def set_status(self):
    items = OrderItem.objects.filter(order=self.pk)
    status = 'ordered'
    statuses = []
    for item in items:
      statuses.append(item.status.name)
    if 'purchased' in statuses:
      status = 'purchased'
    if 'purchasing' in statuses or 'running late' in statuses or 'not available' in statuses:
      status = 'purchasing'
    if 'ordered' in statuses:
      status = 'ordered'
    status_id = Status.objects.get(name=status)
    if status_id != Update.objects.filter(order=self.id).order_by('-time')[0].status:
      Update.objects.create(order=self, status=status_id)
    

  def get_status(self):
    status = Update.objects.filter(order=self.id).order_by('-time')[0].status.name
    return status

  def items(self):
    items = OrderItem.objects.filter(order=self.id)
    return items


class Status(models.Model):
  name = models.CharField(max_length=15)
  style_class = models.TextField()
  
  def __str__(self):
    return self.name

class Update(models.Model):
  order = models.ForeignKey(Order, on_delete=models.CASCADE)
  status = models.ForeignKey(Status, on_delete=models.PROTECT)
  time = models.DateTimeField(auto_now_add=True)


class Note(models.Model):
  order = models.ForeignKey(Order, on_delete=models.CASCADE)
  text = models.TextField()
  courier = models.BooleanField(default=False)


class Supplier(models.Model):
  name = models.CharField(max_length=20, unique=True)

  def __str__(self):
    return self.name

  def get_brands(self):
    brands = Brand.objects.filter(supplier=self.id)
    return brands

class Brand(models.Model):
  name = models.CharField(max_length=20)
  supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT)

  def __str__(self):
    return self.name


class Purchase(models.Model):
  supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT)
  status = models.ForeignKey(Status, on_delete=models.PROTECT)


class OrderItem(models.Model):
  order = models.ForeignKey(Order, on_delete=models.CASCADE)
  name = models.CharField(max_length=100)
  price = models.DecimalField(max_digits=12, decimal_places=2)
  brand = models.ForeignKey(Brand, on_delete=models.PROTECT)
  purchase = models.ForeignKey(Purchase, blank=True, null=True, on_delete=models.PROTECT)
  status = models.ForeignKey(Status, on_delete=models.PROTECT)
  quantity = models.IntegerField()

  def __str__(self):
    return self.name


class PurchaseItem(models.Model):
  orderitem = models.ForeignKey(OrderItem, on_delete=models.CASCADE)
  purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)


### signals ###

def orderitem_post_save(*args, **kwargs):
  kwargs['instance'].order.set_status()

post_save.connect(orderitem_post_save, sender=OrderItem)

def orderitem_post_delete(*args, **kwargs):
  kwargs['instance'].order.set_status()

post_delete.connect(orderitem_post_delete, sender=OrderItem)

templates/orders/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'orders/css/style.css' %}">

  <title>Order Management</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'orders:index' %}">Order Management</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-1 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders:index' %}">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders:purchases' %}">Purchases</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders:suppliers' %}">Suppliers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders:brands' %}">Brands</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container pt-3">
    
    {% block content %}{% endblock %}  
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

templates/orders/brand.html
{% extends "orders/base.html" %}

{% block content %}
  <h3>Brand</h3>
  <div class="form-group">
    <form method="post" class="my-5">
      {% csrf_token %}
      {% for field in form.visible_fields %}
      <div class="row mb-3">
        {{ field.errors }}
        <label for="{{ field.id_for_label }}" class="col-2 col-form-label fw-bold">{{ field.label }}</label>
        <div class="col-auto">
          {{ field }}
        </div>
      </div>
    {% endfor %}
      <div class="col-12 mt-5">
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'orders:brands' %}" class="ms-3 btn btn-danger">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/orders/brands.html
{% extends "orders/base.html" %}

{% block content %}
    <h3>Brands</h3>
    <a href="{% url 'orders:brand-new' %}" class="btn btn-sm btn-outline-primary">New Brand</a>
    {% if brands %}
    <table class="table table-sm table-bordered table-striped w-auto my-3">
      <thead class="table-secondary border-dark">
        <th class="ps-2 pe-5">Name</th>
        <th class="ps-2 pe-5">Supplier</th>
      </thead>
      <tbody>
    {% for brand in brands %}
        <tr>
          <td class="ps-2 pe-5"><a href="{% url 'orders:brand-update' brand.id %}" class="text-decoration-none">{{ brand.name }}</a></td>
          <td class="ps-2 pe-5">{{ brand.supplier.name }}</td>
        </tr>
    {% endfor %}
      </tbody>
    </table>

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&lt;</span>
          </a>
        </li>
        {% endif %}

        {% for page_number in page_obj.paginator.get_elided_page_range %}
          {% if page_number == page_obj.paginator.ELLIPSIS %}
              {{page_number}}
          {% else %}
            <li class="page-item{% if page_obj.number == page_number %} active{% endif %}"><a class="page-link" href="?page={{ page_number }}">{{page_number}}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&gt;</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>

    {% else %}
        <p>There are no brands</p>
    {% endif %}

{% endblock %}

templates/orders/customer.html
{% extends "orders/base.html" %}

{% block content %}
  <h2>Customer</h2>
  <div class="form-group">
    <form method="post" class="my-5">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
        <div class="row mb-3">
          {{ field.errors }}
          <label for="{{ field.id_for_label }}" class="col-2 col-form-label fw-bold">{{ field.label }}</label>
          <div class="col-auto">
            {{ field }}
          </div>
        </div>
      {% endfor %}

      <div class="col-auto mt-5">
        <button type="submit" class="btn btn-success">Save</button>
        {% if order_id > 0 %}
          {% url 'orders:order' order_id as the_url %}
        {% else %}
          {% url 'orders:index' as the_url %}
        {% endif %}
        <a href="{{ the_url }}" class="ms-3 btn btn-danger">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/orders/delete_modal.html
<div class="modal fade" id="{{ modalId }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Do you want to delete?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {{ itemToDelete }}
      </div>
      <div class="modal-footer">
        <form action="{% url deleteUrl idToDelete %}" method="POST">
          {% csrf_token %}
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

templates/orders/index.html
{% extends "orders/base.html" %}

{% block content %}
    <h3>Orders</h3>
    <a href="{% url 'orders:new' %}" class="btn btn-sm btn-outline-primary">New Order</a>

    <table class="table table-sm table-bordered table-striped w-auto my-3">
      <thead class="table-secondary border-dark">
        <th class="ps-2 pe-4">Order</th>
        <th class="ps-2 pe-4">Webshop</th>
        <th class="ps-2 pe-4">Customer</th>
        <th class="ps-2 pe-1">Supplier
          <select id="selectSupplier" class="form-select form-select-sm d-inline w-auto ms-3" aria-label=".form-select-sm example">
            <option {% if not selected_supplier %}selected{% endif %}>- all -</option>
            {% for supplier in suppliers %}
            <option value="{{ supplier.id }}" {% if selected_supplier == supplier.id|stringformat:"i" %}selected{% endif %}>{{ supplier.name }}</option>
            {% endfor %}
          </select>
        </th>
        <th class="ps-2 pe-4">Products</th>
        <th class="ps-2 pe-4">Total</th>
      </thead>
      {% if orders %}
      <tbody>
      {% for order in orders %}
        <tr>
          <td class="ps-2 pe-4"><a href="{% url 'orders:order' order.id %}" class="text-decoration-none">{{ order.id }}</a></td>
          <td class="ps-2 pe-4">{{ order.webshop.name }}</td>
          <td class="ps-2 pe-4">{{ order.customer.name }}</td>
          <td class="ps-2 pe-4">{{ order.get_suppliers|join:", " }}</td>
          <td class="ps-2 pe-4">
            {% for item in order.items %}
            <span class="{{ item.status.style_class}}">{{ item.brand.name }} {{ item.name }}</span>
            {% if forloop.counter < order.items.count %}, {% endif %}
            {% endfor %}
          </td>
          <td class="ps-2 pe-4">£ {{ order.total }}</td>
        </tr>
    {% endfor %}
      </tbody>
    </table>
    {% else %}
    </table>
        <p>No orders are available.</p>
    {% endif %}
    <script>
      document.getElementById('selectSupplier').onchange = function() {
        let params = '';
        if(this.value != '- all -'){
          params = "?supplier=" + this.value;
        }
        window.location = "{% url 'orders:index' %}" + params;
      };
    </script>
{% endblock %}

templates/orders/note.html
{% extends "orders/base.html" %}

{% block content %}
  <h3>Note for order {{ order_id }}</h3>
  <div class="form-group">
    <form method="post" class="my-5">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <input type="hidden" name="order" id="id_order" value="{{ order_id }}" >
      {% for field in form.visible_fields %}
        <div class="row mb-3">
          {{ field.errors }}
          <label for="{{ field.id_for_label }}" class="col-2 col-form-label fw-bold">{{ field.label }}</label>
          <div class="col-auto">
            {{ field }}
          </div>
        </div>
      {% endfor %}
     
      <div class="col-auto mt-5">
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'orders:order' order_id %}" class="ms-3 btn btn-danger">Cancel</a>
       </div>
    </form>
  </div>
{% endblock %}

templates/orders/order.html
{% extends "orders/base.html" %}

{% block content %}
  <h3>Order {{ order.id }}</h3>
  <div class="row mb-3">
    <div class="col-auto"><strong>Webshop: </strong>{{ order.webshop.name }}</div>
    <div class="col-auto ml-5"><strong>Original ID: </strong>{{ order.original }}</div>
    <div class="col-auto ml-5"><strong>Total: </strong>£ {{ order.total }}</div>
    <div class="col-auto ml-5"><strong>Status: </strong>{{ order.get_status }}</div>
    <div class="col-auto ml-5">
      <a href="#" data-bs-toggle="modal" data-bs-target="#updatesModal">Status updates</a>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-auto p-2 m-1 me-5">
      <div class="d-flex justify-content-between pe-1 border-bottom border-secondary mb-2">
        <span class="fs-4">Customer</span>
        <a href="{% url 'orders:customer-update' customer.id%}" class="btn btn-link">Edit</a>
      </div>
      <div class="pe-3">
        <table class="table table-borderless table-sm">
          <tbody>
            <tr>
              <td class="fw-bold">Name</td>
              <td>{{ customer.name }}</td>
            </tr>
            <tr>
              <td class="fw-bold">Email</td>
              <td>{{ customer.email }}</td>
            </tr>
            <tr>
              <td class="fw-bold">Phone</td>
              <td>{{ customer.phone }}</td>
            </tr>
            <tr>
              <td class="fw-bold">Address</td>
              <td>{{ customer.address }}<br />{{ customer.city }}<br />{{ customer.postcode }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-auto p-2 m-1">
      <div class="d-flex justify-content-between pe-1 border-bottom border-secondary mb-2">
        <span class="fs-4">Ordered items</span>
        <a href="{% url 'orders:orderitem-create' order_id=order.id %}" class="btn btn-link">Add item</a>
      </div>
      <div class="pe-3">
        <table class="table table-borderless table-sm">
          <thead>
            <tr>
              <th>Product</th>
              <th>Price</th>
              <th>Quantity</th>
              <th>Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for item in items %}
            <tr>
              <td>{{ item.brand.name }} {{ item.name }}</td>
              <td>£ {{ item.price }}</td>
              <td class="text-center">{{ item.quantity }}</td>
              <td class="{{ item.status.style_class}}">{{ item.status.name }}</td>
              <td>
                <a href="{% url 'orders:orderitem-update' item.id %}">Edit</a>
                <a href="#" class="text-danger ms-3" data-bs-toggle="modal" data-bs-target="#deleteItem{{ item.id }}">Delete</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>  
  </div>
  
  <div class="row">
    <div class="col-auto p-2 m-1 me-5">
      <div class="d-flex justify-content-between pe-1 border-bottom border-secondary mb-2">
        <span class="fs-4">Notes</span>
        <a href="{% url 'orders:note-create' order_id=order.id %}" class="btn btn-link">Add note</a>
      </div>
      <div class="pe-3">
        <table class="table table-borderless table-sm">
          <thead>
            <tr>
              <th>Note</th>
              <th>For courier</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% if notes %}
              {% for note in notes %}
                <tr>
                  <td>{{ note.text }}</td>
                  <td class="text-center">{% if note.courier %}<i class="bi bi-check-square"></i>{% endif %}</td>
                  <td>
                    <a href="{% url 'orders:note-update' note.id %}">Edit</a>
                    <a href="#" class="text-danger ms-3" data-bs-toggle="modal" data-bs-target="#deleteNote{{ note.id }}">Delete</a>
                  </td>
                </tr>
              {% endfor %}
            {% else %}
              <tr>
                <td>-</td>
                <td>-</td>
              </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

    {% for item in items %}
      {% with itemId=item.id|stringformat:"i"  %}
        {% include "orders/delete_modal.html" with modalId="deleteItem"|add:itemId itemToDelete=item.brand.name|add:" "|add:item.name deleteUrl="orders:orderitem-delete" idToDelete=item.id %}
      {% endwith %}
    {% endfor %}

    {% for note in notes %}
      {% with noteId=note.id|stringformat:"i"  %}
        {% include "orders/delete_modal.html" with modalId="deleteNote"|add:noteId itemToDelete=note.text deleteUrl="orders:note-delete" idToDelete=note.id %}
      {% endwith %}
    {% endfor %}

    <div class="modal fade" id="updatesModal" tabindex="-1" aria-labelledby="updatesModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="updatesModalLabel">Status updates</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <table class="table table-borderless table-sm">
              <thead class="table-secondary">
                <tr>
                  <th>Date - time</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {% for update in updates %}
                <tr>
                  <td class="pe-5">{{ update.time|date:"d/m/Y - H:i" }}</td>
                  <td>{{ update.status }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    
 
  
  {% endblock %}

templates/orders/orderitem.html
{% extends "orders/base.html" %}

{% block content %}
  <h2>Item for order {{ order_id }}</h2>
  <div class="form-group">
    <form method="post" class="my-5">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <input type="hidden" name="order" id="id_order" value="{{ order_id }}" >
      {% for field in form.visible_fields %}
        <div class="row mb-3">
          {{ field.errors }}
          <label for="{{ field.id_for_label }}" class="col-2 col-form-label fw-bold">{{ field.label }}</label>
          <div class="col-auto">
            {{ field }}
          </div>
        </div>
      {% endfor %}
     
      <div class="col-auto mt-5">
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'orders:order' order_id %}" class="ms-3 btn btn-danger">Cancel</a>
       </div>
    </form>
  </div>
{% endblock %}

templates/orders/purchases.html
{% extends "orders/base.html" %}

{% block content %}
    <h3>Purchases</h3>
    <a href="#" class="btn btn-sm btn-outline-primary">New Purchase</a>
    {% if purchases %}
    <table class="table table-sm table-bordered table-striped w-auto my-3">
      <thead class="table-secondary border-dark">
        <th class="ps-2 pe-5">Supplier</th>
        <th class="ps-2 pe-5">Total</th>
      </thead>
      <tbody>
    {% for purchase in purchases %}
        <tr>
          <td class="ps-2 pe-5">{{ purchase.supplier.name }}</td>
          <td class="ps-2 pe-5">£ 45.99</td>
        </tr>
    {% endfor %}
      </tbody>
    </table>

    <nav aria-label="Purchases page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&lt;</span>
          </a>
        </li>
        {% endif %}

        {% for page_number in page_obj.paginator.get_elided_page_range %}
          {% if page_number == page_obj.paginator.ELLIPSIS %}
              {{page_number}}
          {% else %}
            <li class="page-item{% if page_obj.number == page_number %} active{% endif %}"><a class="page-link" href="?page={{ page_number }}">{{page_number}}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&gt;</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>

    {% else %}
        <p>There are no purchases</p>
    {% endif %}

{% endblock %}

templates/orders/supplier.html
{% extends "orders/base.html" %}

{% block content %}
  <h3>Supplier</h3>
  <div class="form-group">
    <form method="post" class="my-5">
      {% csrf_token %}
      {% for field in form.visible_fields %}
      <div class="row mb-3">
        {{ field.errors }}
        <label for="{{ field.id_for_label }}" class="col-2 col-form-label fw-bold">{{ field.label }}</label>
        <div class="col-auto">
          {{ field }}
        </div>
      </div>
    {% endfor %}
      <div class="col-12 mt-5">
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'orders:suppliers' %}" class="ms-3 btn btn-danger">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/orders/suppliers.html
{% extends "orders/base.html" %}

{% block content %}
    <h3>Suppliers</h3>
    <a href="{% url 'orders:supplier-new' %}" class="btn btn-sm btn-outline-primary">New Supplier</a>
    {% if suppliers %}
    <table class="table table-sm table-bordered table-striped w-auto my-3">
      <thead class="table-secondary border-dark">
        <th class="ps-2 pe-5">Supplier Name</th>
        <th class="ps-2 pe-5">Brands</th>
      </thead>
      <tbody>
    {% for supplier in suppliers %}
      <tr>
        <td class="d-flex justify-content-between px-2">
          <a href="{% url 'orders:supplier-update' supplier.id%}" class="text-decoration-none">{{ supplier.name }}</a>
          {% if not supplier.get_brands %}
          <a href="#" class="text-decoration-none text-danger ms-5" data-bs-toggle="modal" data-bs-target="#deleteSupplier{{ supplier.id }}">Delete</a>
          {% endif %}
        </td>
        <td class="ps-2 pe-5">{{ supplier.get_brands|join:", " }}</td>
      </tr>
      {% with supplierId=supplier.id|stringformat:"i"  %}
        {% include "orders/delete_modal.html" with modalId="deleteSupplier"|add:supplierId itemToDelete=supplier.name deleteUrl="orders:supplier-delete" idToDelete=supplier.id %}
      {% endwith %}
    {% endfor %}
      </tbody>
    </table>
    {% else %}
       <p>There are no suppliers</p>
    {% endif %}

{% endblock %}